site_name: SignalRKore
site_description: Kotlin Multiplatform client library for ASP.NET Core SignalR
site_author: Michal Lepíček
site_url: https://lepicekmichal.github.io/SignalRKore/
repo_name: lepicekmichal/SignalRKore
repo_url: https://github.com/lepicekmichal/SignalRKore
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: teal
    accent: teal
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - tables
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Connection: user-guide/connection.md
    - Sending Messages: user-guide/sending-messages.md
    - Receiving Messages: user-guide/receiving-messages.md
    - Streams: user-guide/streams.md
    - Reconnection: user-guide/reconnection.md
    - Configuration: user-guide/configuration.md
  - API Reference:
    - HubConnection: api/hub-connection.md
    - HubConnectionBuilder: api/hub-connection-builder.md
    - Transport: api/transport.md
    - Protocol: api/protocol.md